language: php

services:
    - mysql
    - postgresql

cache:
    directories:
        - $HOME/.composer/cache/files

env:
    global:
        - DB_CONNECTION=sqlite
        - DB_CONNECTION=":memory:"

php:
    - 7.2
    - 7.3
    - 7.4snapshot

matrix:
    include:
        - php: 7.2
          env: COMPOSER_FLAGS="--prefer-lowest" DB_CONNECTION=mysql DB_DATABASE=test DB_USERNAME=root DB_PASSWORD=
        - php: 7.2
          env: COMPOSER_FLAGS="--prefer-lowest" DB_CONNECTION=pgsql DB_DATABASE=test DB_USERNAME=postgres DB_PASSWORD=
        - php: 7.3
          env: COMPOSER_FLAGS="--prefer-lowest" DB_CONNECTION=mysql DB_DATABASE=test DB_USERNAME=root DB_PASSWORD=
        - php: 7.3
          env: COMPOSER_FLAGS="--prefer-lowest" DB_CONNECTION=pgsql DB_DATABASE=test DB_USERNAME=postgres DB_PASSWORD=
    allow_failures:
        - php: 7.4snapshot

before_install:
    - mysql -e 'CREATE DATABASE test;'
    - psql -c 'create database test;' -U postgres

install:
    - travis_retry composer self-update
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction

script:
    - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover